version: '3'
services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    expose:
      - '5432'
    ports:
      - '54321:5432'
    networks:
      - custom_network
    environment:
      - PG_PASSWORD=password
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s

networks:
  custom_network:
    external: false
    name: custom_network
